In [ ]:
from pathlib import Path
from collections import Counter
import pandas as pd

from battery_aging.data_preprocessing import load_dataset


Dataset = "Stanford"
data_folder = Path("..", "Battery_life_Dataset", Dataset)

datasets = load_dataset(
    data_folder,
    n_files="all",
    seed=42
)

protocols = [
    str(d["discharge_protocol"])
    for d in datasets
]

stanford_protocols = pd.DataFrame(
    Counter(protocols).items(),
    columns=["Discharge Protocol", "Frequency"]
)

stanford_protocols

                                  Discharge Protocol  Frequency
0  [{'rate_in_C': 0.75, 'current_in_A': None, 'vo...         41

In [7]:
# print("Cell ID:", stanford_protocols["Discharge Protocol"])

print(datasets[0]["discharge_protocol"])

[{'rate_in_C': '', 'current_in_A': None, 'voltage_in_V': None, 'power_in_W': None, 'start_voltage_in_V': None, 'start_soc': 1.0, 'end_voltage_in_V': None, 'end_soc': 1}]

In [2]:
Dataset = "HUST"
data_folder = Path("..", "Battery_life_Dataset", Dataset)

datasets = load_dataset(
    data_folder,
    n_files="all",
    seed=42
)

protocols = [
    str(d["discharge_protocol"])
    for d in datasets
]

hust_protocols = pd.DataFrame(
    Counter(protocols).items(),
    columns=["Discharge Protocol", "Frequency"]
)

hust_protocols

                                   Discharge Protocol  Frequency
0   [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
1   [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
2   [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
3   [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
4   [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
..                                                ...        ...
72  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
73  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
74  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
75  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
76  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1

[77 rows x 2 columns]

In [3]:
Dataset = "Tongji"
data_folder = Path("..", "Battery_life_Dataset", Dataset)

datasets = load_dataset(
    data_folder,
    n_files="all",
    seed=42
)

protocols = [
    str(d["discharge_protocol"])
    for d in datasets
]

tongji_protocols = pd.DataFrame(
    Counter(protocols).items(),
    columns=["Discharge Protocol", "Frequency"]
)

tongji_protocols

                                  Discharge Protocol  Frequency
0  [{'rate_in_C': '', 'current_in_A': None, 'volt...        130

In [4]:
protocol_comparison = pd.concat(
    [
        stanford_protocols.assign(Dataset="Stanford"),
        hust_protocols.assign(Dataset="HUST"),
        tongji_protocols.assign(Dataset="Tongji")
    ],
    ignore_index=True
)

protocol_comparison[
    ["Dataset", "Discharge Protocol", "Frequency"]
]

     Dataset                                 Discharge Protocol  Frequency
0   Stanford  [{'rate_in_C': 0.75, 'current_in_A': None, 'vo...         41
1       HUST  [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
2       HUST  [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
3       HUST  [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
4       HUST  [{'rate_in_C': 5.0, 'current_in_A': None, 'vol...          1
..       ...                                                ...        ...
74      HUST  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
75      HUST  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
76      HUST  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
77      HUST  [{'rate_in_C': 3.0, 'current_in_A': None, 'vol...          1
78    Tongji  [{'rate_in_C': '', 'current_in_A': None, 'volt...        130

[79 rows x 3 columns]